ordering:
  home: ''
  pages: ''
  business: ''
  customer: ''
  register: ''
items:
  home:
    id: 101
    hash: ''
    width: auto
    class: ''
  customer:
    id: 104
    hash: ''
    width: auto
    class: ''
  pages:
    id: 110
    hash: ''
    dropdown: fullwidth
    dropdown_hide: ''
    width: 360px
    class: ''
  business:
    id: 123
    hash: ''
    dropdown: fullwidth
    width: auto
    class: ''
  styles/__particle-muOvm:
    type: particle
    particle: custom
    title: 'Custom HTML'
    options:
      particle:
        enabled: '1'
        html: "<div class=\"g-grid g-preset-thumbnails\">\n    <div class=\"g-block\">\n        <div class=\"g-content\">\n            <a href=\"?presets=preset1\">\n                <img src=\"images/rocketlauncher/styles/preset1.jpg\" alt=\"Preset 1\">\n                <br>\n                <span>Preset 1</span>\n            </a>\n        </div>\n    </div>\n    <div class=\"g-block\">\n        <div class=\"g-content\">\n            <a href=\"?presets=preset2\">\n                <img src=\"images/rocketlauncher/styles/preset2.jpg\" alt=\"Preset 2\">\n                <br>\n                <span>Preset 2</span>\n            </a>\n        </div>\n    </div>\n    <div class=\"g-block\">\n        <div class=\"g-content\">\n            <a href=\"?presets=preset3\">\n                <img src=\"images/rocketlauncher/styles/preset3.jpg\" alt=\"Preset 3\">\n                <br>\n                <span>Preset 3</span>\n            </a>\n        </div>\n    </div>\n    <div class=\"g-block\">\n        <div class=\"g-content\">\n            <a href=\"?presets=preset4\">\n                <img src=\"images/rocketlauncher/styles/preset4.jpg\" alt=\"Preset 4\">\n                <br>\n                <span>Preset 4</span>\n            </a>\n        </div>\n    </div>\n    <div class=\"g-block\">\n        <div class=\"g-content\">\n            <a href=\"?presets=preset5\">\n                <img src=\"images/rocketlauncher/styles/preset5.jpg\" alt=\"Preset 5\">\n                <br>\n                <span>Preset 5</span>\n            </a>\n        </div>\n    </div>\n    <div class=\"g-block\">\n        <div class=\"g-content\">\n            <a href=\"?presets=preset6\">\n                <img src=\"images/rocketlauncher/styles/preset6.jpg\" alt=\"Preset 6\">\n                <br>\n                <span>Preset 6</span>\n            </a>\n        </div>\n    </div>\n</div>"
      block:
        extra: {  }
