preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home_positions
  timestamp: 1441941680
children:
  -
    id: 0ab39ee5-cde5-3e39-6587-381962e907cf
    type: section
    subtype: false
    title: Top
    attributes:
      boxed: '0'
      class: ''
      extra: {  }
    children: {  }
  -
    id: 5146ebf2-fe84-aa62-bdf4-8178eab530f2
    type: section
    subtype: false
    title: Navigation
    attributes:
      boxed: '0'
      class: ''
      extra: {  }
    children: {  }
  -
    id: a875dce8-82c8-88cb-88cc-888f7c9828f8
    type: section
    subtype: false
    title: Header
    attributes:
      boxed: 0
    children: {  }
  -
    id: 71fa8c64-3ff4-6683-bb80-258c17267929
    type: container
    subtype: false
    title: Untitled
    attributes:
      boxed: '0'
      class: fp-slideshow-blocks
      extra:
        -
          id: g-slideshow
    children:
      -
        id: 31222a3d-67cf-83f6-8604-7c5e2ee8dabb
        type: grid
        subtype: false
        title: Untitled
        attributes: {  }
        children:
          -
            id: 32c242bd-7b7f-e873-45ff-7ba091f41bf1
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 25
            children:
              -
                id: aca65835-9782-15a8-e6c9-737fcf1f93ea
                type: section
                subtype: false
                title: SlideLeft
                attributes:
                  class: ''
                  extra: {  }
                children: {  }
          -
            id: b186da4c-b8f1-67ae-c725-47dc7f8f80ef
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 50
            children:
              -
                id: e628a8f5-fe23-ba7a-6dfd-99b3709e654a
                type: section
                subtype: false
                title: SlideCenter
                attributes:
                  class: ''
                  extra: {  }
                children: {  }
          -
            id: 7496e1a8-2ee5-bb0a-227f-4cf7ebbd3c45
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 25
            children:
              -
                id: 1d27062c-b652-55a8-049b-ad7177a5262a
                type: section
                subtype: false
                title: SlideRight
                attributes:
                  class: ''
                  extra: {  }
                children: {  }
  -
    id: 2a3fffe7-b2c4-c8cf-76cc-c25f7c9828f4
    type: section
    subtype: false
    title: Showcase
    attributes:
      boxed: 0
    children:
      -
        id: a9d9f69d-80ee-4b42-a3a2-c20c959aef51
        type: grid
        subtype: false
        title: Untitled
        attributes: {  }
        children:
          -
            id: 02dcb079-fddb-4523-be8e-36e64d5ab222
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 100
            children:
              -
                id: 2e910757-8e9e-4db0-b395-7c7b5ea2e3c0
                type: pagecontent
                subtype: pagecontent
                title: 'Page Content'
                attributes: {  }
                children: {  }
  -
    id: 5a754282-2da7-0a53-5111-a731c4b9443b
    type: section
    subtype: false
    title: Above
    attributes:
      boxed: 0
    children: {  }
  -
    id: 8888ddf8-c1d4-e8ab-88aa-c88f7c9828f8
    type: section
    subtype: false
    title: Utility
    attributes:
      boxed: '0'
      class: ''
      extra: {  }
    children: {  }
  -
    id: 3b4dddf8-c1d4-e8ab-88aa-c88f7c9828f8
    type: section
    subtype: false
    title: Feature
    attributes:
      boxed: '0'
      class: ''
      extra: {  }
    children: {  }
  -
    id: 4bf3811a-a93a-15bc-6cd5-c72837ecaa12
    type: container
    subtype: false
    title: Untitled
    attributes:
      boxed: 0
    children:
      -
        id: 4e392a61-a7b8-49a6-c651-6f9fa9deb615
        type: grid
        subtype: false
        title: Untitled
        attributes: {  }
        children:
          -
            id: af745017-c9f0-0033-7a89-3727e34d803d
            type: block
            subtype: false
            title: Untitled
            attributes:
              extra: {  }
              size: 5
            children:
              -
                id: 23b41892-0579-7204-936d-d51221df6843
                type: section
                subtype: false
                title: Sidebar
                attributes:
                  class: ''
                  extra: {  }
                children: {  }
          -
            id: 5ce5aef7-c18b-d523-eae5-23a8f21f1776
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 90
            children:
              -
                id: 9b7b28a6-47ed-0a02-721d-9460d0cd26f0
                type: section
                subtype: false
                title: Mainbar
                attributes:
                  class: fp-mainbar
                  extra: {  }
                children: {  }
          -
            id: b4033baa-a997-0462-11c2-4948674569d5
            type: block
            subtype: false
            title: Untitled
            attributes:
              extra: {  }
              fixed: '1'
              size: 5
            children:
              -
                id: 03156c2b-585c-810b-36e2-edd46f8e9fdd
                type: section
                subtype: false
                title: Aside
                attributes:
                  class: ''
                  extra: {  }
                children: {  }
  -
    id: 28a0de88-8f18-8bf8-84b8-c5a67880f9d8
    type: section
    subtype: false
    title: Expanded
    attributes:
      boxed: 0
    children: {  }
  -
    id: 68a0de11-cf1d-cbfa-84b0-a5a67990f9d8
    type: section
    subtype: false
    title: Extension
    attributes:
      boxed: '0'
      class: fp-extension
      extra: {  }
    children: {  }
  -
    id: 618a6182-88ab-bda8-88ba-e88ac28a3c8c
    type: section
    subtype: false
    title: Bottom
    attributes:
      boxed: 0
    children: {  }
  -
    id: a9ae9244-8b06-ce7a-6775-fcf4d67259f7
    type: container
    subtype: false
    title: Untitled
    attributes:
      boxed: 0
    children:
      -
        id: 5b13e4cb-c20d-6e0f-82c0-c552c6f7caf0
        type: grid
        subtype: false
        title: Untitled
        attributes: {  }
        children:
          -
            id: c03265e3-00c4-edce-dcfb-2d2bc229edc5
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 50
            children:
              -
                id: 510ada67-7713-516a-b197-43c2960958d8
                type: section
                subtype: false
                title: Footer
                attributes: {  }
                children: {  }
          -
            id: d653392d-d37a-bfaa-55e5-f3e085e90dc2
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 50
            children:
              -
                id: 16813637-d936-d4a8-1d65-b4133cae4097
                type: section
                subtype: false
                title: Footside
                attributes: {  }
                children: {  }
  -
    id: a73b36ef-b6e6-8ec5-cc6d-6ccc083e669c
    type: section
    subtype: false
    title: Copyright
    attributes:
      boxed: 0
    children: {  }
  -
    id: e4a7e190-0847-5f74-c5ac-16aa482a19d4
    type: offcanvas
    subtype: false
    title: Offcanvas
    attributes:
      name: 'Offcanvas Section'
      boxed: 0
    children: {  }
  -
    id: 9636f3e2-bfb3-4d39-c303-2356e0909c42
    type: atoms
    subtype: false
    title: Atoms
    attributes:
      name: 'Atoms Section'
      boxed: 0
    children:
      -
        id: 0a320a69-87db-49d8-b5fb-118478761346
        type: grid
        subtype: false
        title: Untitled
        attributes: {  }
        children: {  }
